mongodb/js-bson

lib/bson/objectid.js, test/node/bson_test.js
Prevent objects with a `length` key of 12 or 24 to be considered valid ObjectIDs.
=> Change ObjectID.isValid to reject objects with specific keys

lib/bson/objectid.js
As @williamkapke mentioned in https://github.com/williamkapke/bson-objectid/issues/6#issuecomment-161053746, there's a small mistake that could possibly cause the pid in a browser environment to be set to a value greater than 0xFFFF.
In bson-objectid, it caused it to incorrectly generate 26-character ObjectID's. I'm not sure if it causes a problem here but I'm making a PR with the fix anyway to be safe.
=> Fixed browser pid sometimes set greater than 0xFFFF

bower.json
This fixes #135. The main benefit of this is the `main` field, such that build tools (wiredep) can automatically insert a bson dependency in your html.
=> Add bower.json to this package to enable usage as a bower dependency

lib/bson/index.js
https://github.com/mongodb/js-bson/issues/122
https://github.com/Automattic/mongoose/issues/3713
https://github.com/johnpapa/ng-demos/issues/27 (a similar problem)
Seems like these dot slashes are unneccesary. Multiple dot-slashes (`./././`) should be equal to single (`./`), but they are the cause of broken builds if webpack is used.
```
caulfield-osx:test caulfield$ node build/server.js
/Users/caulfield/www/test/build/server.js:35054
return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
^
Error: Cannot find module '././binary_parser'.
at /Users/caulfield/www/test/build/server.js:35054:42
at webpackContextResolve (/Users/caulfield/www/test/build/server.js:35054:90)
at webpackContext (/Users/caulfield/www/test/build/server.js:35051:30)
at …
```
=> Remove unnecessary dot slashes in paths

lib/bson/parser/deserializer.js
In the event that you are providing a `Buffer` and non-zero `startIndex` to `deserialize` or `deserializeStream`, if the `startIndex` points to a valid BSON document, it will incorrectly error out saying `"One object, sized correctly, with a spot for an EOO, but the EOO isn't 0x00"`
This PR fixes that.
=> When deserializing an arbitary index in a buffer, stay relative to the index

lib/bson/objectid.js, test/node/bson_test.js
The fact that `ObjectID.isValid(new ObjectID());` returns false seems a little weird, re: https://github.com/Automattic/mongoose/issues/1959#issuecomment-170195451
=> fix(ObjectID): isValid(new ObjectID()) returns true

lib/bson/binary.js
Fix for #152. Hopefully makes authentication possible when using the driver within Electron.
=> Fix "TypeError: data.copy is not a function" in Electron

lib/bson/objectid.js, test/node/bson_test.js
This PR uses duck-typing to better support `new ObjectID` and `isValid`. It uses logic already present in the `equals` implementation and brings it in the `constructor` and the `isValid`.
The main reason why this is needed is to support the following case:
```
var m1 = require('mongodb')
var m2 = require('./node_modules/MODULE/node_modules/mongodb')
var hash = '56facc09cb986a0051a19c10';
m1.ObjectID.isValid(new m2.ObjectID(hash)) // Returns false! Should return true!
new m1.ObjectId(new m2.ObjectId(hash)) // Throws it should just return an ObjectId
```
=> Support isValid and new ObjectId accross different versions and instances of the bson package

lib/bson/objectid.js
Improving previous PR to take advantage of the validation already done in the `isValid`
=> fix(ObjectID): isValid(new ObjectID()) returns true - Improve duck-typing in constructor

lib/bson/objectid.js
This is a rather common scenario and perf gain is around 3x - 4x faster
=> ObjectID(x) where is an ObjectID-like makes a useless memory allocation

lib/bson/objectid.js
Among the values to guarantee the uniqueness of ObjectID is pid.
However, in a docker environment, the pid of most processes has a value of 1.
If pid is 1, it uses random value.
https://github.com/mongodb/js-bson/issues/212
=> Maintain uniqueness in a docker environment

lib/bson/bson.js, test/node/serialize_with_buffer_tests.js
We first serialize the object into a buffer `buffer`, and then copy the object into `finalBuffer`. The issue here was that we serialized the object into `buffer` beginning at startIndex, but then copied into `finalBuffer` beginning at 0, meaning data previously written to `buffer` would be copied into 
`finalBuffer` rather than the desired document. 
(The existing test did not catch this because it used two identical documents.) 
This fix works by just always writes into `buffer` starting at 0.
=> fix(serializeWithBufferAndIndex): write documents to start of intermediate buffer

lib/bson/parser/deserializer.js, test/node/bson_test.js
using this module in mongodb-extjson, I realized that my previous updates to the code did not correctly convert { dbref: { $ref: .., $id:... }} to BSON.DBRef objects. the test failed to catch this because it was just checking that fields matched up rather than checking for deep equality, so I have fixed that as well.
=> fix(dbref): correctly upgrade dbrefs to BSON.DBRef

README.md
I'd love to have something to link to that explains the rationale behind the `undefined` -> `null` conversion re: issues like https://github.com/Automattic/mongoose/issues/5776 .
=> docs: add FAQ re: `undefined`

README.md
This updates the readme to mention the native version of the parser as well as clean up the copy a bit 📖 
There is a related PR to the native parser: https://github.com/mongodb-js/bson-ext/pull/39
NODE-995
=> docs(readme): mention native parser, cleanup copy

lib/bson/db_ref.js, lib/bson/parser/deserializer.js, lib/bson/parser/serializer.js, lib/bson/regexp.js
required updates to use this module within the `bson-ext` C++ extension.
=> Updates for bson ext

lib/bson/bson.js
Removed an unnecessary copy to the internal buffer and then back to the final buffer when using serializeWithBufferAndIndex
=> Optimization for serializeWithBufferAndIndex

README.md
I haven't been able to find any docs about `toBSON()`, so I figure this is as good a place to add it as any.
=> docs: add FAQ about toBSON()

alternate_parsers/bson.js, lib/bson/binary.js, lib/bson/decimal128.js, lib/bson/objectid.js, lib/bson/parser/serializer.js
[this PR is a rebase (and update) of PR #157]
When constructing a new `ObjectId` object, the passed id value is validated for conversion to an hex string.
This is just fine, however a generic Error object is thrown when this validation fails.
Tracking the error then becomes unconvenient.
From official [Joyent's design patterns for errors](https://www.joyent.com/developers/node/design/errors), it is suggested that:
> 3. Use the Error's name property to distinguish errors programmatically.
>    When you need to figure out what kind of error this is, use the name property.
>    Built-in JavaScript names you may want to reuse include "RangeError"
>    (an argument is outside of its valid range) and "TypeError" (an argument has the wrong type).
>    For HTTP errors, it's common to use the …
=> use the more specific `TypeError` objects for function parameters errors.

lib/bson/bson.js, lib/bson/parser/deserializer.js, test/binary_parser.js, test/node/bson_test.js
deserializeStream was calling deserialize, which required the buffer
size to exactly match the object size per the corpus test. Fixing
this by adding a flag that deserializeStream passes to allow the
buffer to be larger than the object size.
Fixes #244
=> fix(deserializeStream): allow multiple documents to be deserialized

lib/bson/objectid.js, lib/bson/symbol.js
The currently used custom inspect way is deprecated and was removed
in Node.js 11.0.0-pre. This should fix that.
=> fix(bson): fix custom inspect property

lib/bson/parser/utils.js, test/node/bson_test.js
Update normalizedFunctionString to correctly normalize the string
representation of named functions.
Fixes NODE-1552
=> fix(bson): normalizedFunctionString handles named functions

tools/scenarios-plugin.js
Uses findScenarios function from tools/bson_corpus_loader.js instead of
rewriting it in the scenariosPlugin.
Fixes NODE-1504
=> refactor(bson): minimize repeated code in testing

lib/binary.js, lib/bson.js, lib/code.js, lib/db_ref.js, lib/decimal128.js, lib/double.js, lib/extended_json.js, lib/int_32.js, lib/long.js, lib/max_key.js, lib/min_key.js, lib/objectid.js, lib/regexp.js, lib/symbol.js, lib/timestamp.js, test/node/bson_corpus_tests.js, test/node/extended_json_tests.js
This is a big code merge, but I believe it would dramatically reduce our maintenance load and we are already making a major version bump here. Generally the code changes would go from:
```
const EJSON = require('mongodb-extjson');
EJSON.stringify(...);
EJSON.parse(...);
```
to
```
const { EJSON } = require('bson');
EJSON.stringify(...);
EJSON.parse(...);
```
=> feat(ext-json): merge extended JSON into js-bson

lib/extended_json.js, test/node/extended_json_tests.js
This ensures we take relaxed/strict mode into account when
deserializing a double, similar to the integer checks above it.
NODE-1639
=> fix(ext-json): deserialize doubles as `Number` in relaxed mode

lib/objectid.js, test/node/object_id_tests.js
```
const buff = Buffer.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
// returns true
ObjectId.isValid(buff) 
// TypeError: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
new ObjectId(buff)
```
=> ObjectId.isValid should check buffter length

lib/parser/deserializer.js, lib/validate_utf8.js, test/node/string_test.js
When deserializing a string, we previously relied on the appearance
of 0xFFFD to denote an invalid unicode character. However, 0xFFFD
is a valid unicode character if that is what was originally
input.
Fixes NODE-1718
Fixes #277
=> fix(deserialize): fix deserialization of 0xFFFD

lib/objectid.js, test/node/object_id_tests.js
If a non-hex string of length 12 is passed into the ObjectId
constructor, we generate a hexString based off of the character
codes of the passed in id. This requires that the passed id consist
entirely of characters with values < 256 in utf-16. Previously,
we let this silently fail and generated invalid hex string. Now,
we throw a TypeError
Fixes NODE-1737
BREAKING CHANGE:
Where code was previously silently erroring, users may now
experience TypeErrors
=> fix(ObjectId): will now throw if an invalid character is passed

.eslintrc, lib/objectid.js, lib/parser/serializer.js, test/node/bson_test.js
`ObjectId` in previous versions of the library had a `bsontype` of `ObjectID` (note the capital lettering at the end). The new library needs to be updated to reflect this.
=> fix(object-id): correct serialization of old ObjectID types

lib/extended_json.js, test/node/extended_json_tests.js
Currently, passing an array form of the `replacer` parameter of `EJSON.stringify` will not work, despite the documentation saying that it should work.  The cause is that the current implementation checks whether `replacer` is of type `object`, and if it is then it assumes that the `replacer` parameter is really the `options` parameter (meaning that `replacer` and `space` have been omitted by the user).  This logic breaks when `replacer` is an array (which is an `object` too). 
To fix this problem I added a check using `Array.isArray` so the replacement above will only happen if `replacer` is an object that's not an array. 
While I was editing this method, I also changed the weird (and eslint-defying) use of assignment expressions like this: 
`if (space != null && typeof space === …
=> Fix EJSON.stringify if replacer is array (not function)

lib/extended_json.js, test/node/extended_json_tests.js
This PR fixes #302 (Extended JSON serializer runs twice for every nested document) by refactoring EJSON serialization to remove the ignored first serialization and to remove the duplicated code that was producing the ignored first serialization.
Although all existing tests still pass, I didn't add any new tests because the only externally-visible change from this PR should be faster serialization-- the library itself should work the same.
I also noticed two other potential problems that I didn't know how to fix, so I added TODO comments that can be addressed in later PRs.
This PR's code changes overlap with #304, but the overlapping lines are the same in both--and neither PR is dependent on the other--so they should merge together or individually without conflicts.
=> Stop running Extended JSON serializer twice for each nested document

lib/objectid.js, test/node/object_id_tests.js
Avoid treating timestamps with the most significant bit set as negative. The mongodb documentation describe the timetsamp portion of objectids as 'seconds since the unix epoch', so this seems to be the correct behaviour, although I cannot find a formal specification for it.
However this is technically a breaking change if people were relying on timestamp values before 1970.
=> Fix getTimestamp for times beyond 2038

lib/binary.js, lib/objectid.js, package.json, test/node/bson_corpus_tests.js, test/node/extended_json_tests.js, test/node/object_id_tests.js
Node has deprecated the `inspect` property on objects for use in `util.inspect()`. Doing so on an ObjectID on Node v10 prints a deprecation warning:
```
(node:16945) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```
This fixes it to use the new symbol that is exposed by `util.inspect` instead - and fallback to the string property for old node versions.
=> Fix: deprecation warnings for buffers and util.inspect

browser_build/bson.js, lib/bson/parser/calculate_size.js, lib/bson/parser/serializer.js, test/node/4x-interop/objectid.js, test/node/4x-interop/parser/utils.js, test/node/bson_test.js
This PR for the 1.0 branch fixes #310 (which prevents 4.x from sending MinKey values to the current Node driver).  Unlike every other interop issue I found while building #312, `MinKey` didn't have an obvious workaround without changing the 1.x library (and bumping deps and re-releasing `mongodb-core` and `mongodb` packages).
While fixing the `MinKey` issue above, I also added interop support 4.0.0 and 4.0.1 `ObjectId._bsontype` so that either `ObjectID` or `ObjectId` values for `_bsontype` will be accepted by the 1.x library.  This doesn't remove the need to merge #312 (which contains fixes for duck-typed libraries and other BSON types) but does make things less broken for existing 4.0 users before they upgrade to a 4.x release that includes #312.
Tests for the fixes above are included. …
=> Patch 1.x branch to fix 4.x->1.x interop for MinKey and ObjectId

lib/timestamp.js, test/node/timestamp_tests.js
=> fix(Timestamp): make sure timestamp is always unsigned

README.md
Documents the different ways to use the bson library across
different platforms, including node, browser, and webpack.
Fixes NODE-2058
=> docs(usage): more clearly document usage for various platforms

README.md, lib/binary.js, lib/db_ref.js, lib/double.js, lib/extended_json.js, lib/int_32.js, lib/regexp.js, package-lock.json, test/node/extended_json_tests.js
- Adds a `legacy: true` option to `serialize`, `deserialize`, `parse`, and `stringify`.
- Adds tests for cases where v1 and v2 extjson differ.
=> NODE-2253: Support for v1 Extended JSON

lib/double.js, lib/int_32.js, test/node/double_tests.js, test/node/int_32_tests.js
Numbers objects deserve the same love and support as their primitive
counterparts. So handle them appropriately without introducing
regressions into behaviors of other types that may be passed in as
values
Fixes NODE-2384
=> fix: Support Number object in Int32 and Double constructors

lib/double.js, lib/parser/deserializer.js, test/node/bson_corpus_tests.js, test/node/bson_test.js, test/node/map_tests.js, test/node/specs/bson-corpus/multi-type-deprecated.json
A decision made early in the refactoring of this module for v2 (now v4) lead us to always upgrade `BSONSymbol` to a JavaScript `String`. This is problematic because the type can no longer be round tripped to and from raw BSON bytes. This changeset puts the automatic upgrading behind an existing flag, `promoteValues`, which is already used in a number of places to do this type of lossy conversion.
The last commit is the real change, but a number of other changes were made along the way to fix the bson corpus test runner.
=> NODE-2518: preserve type information when round tripping symbols

lib/int_32.js, test/node/extended_json_tests.js, test/node/int_32_tests.js
This update adds `parseInt` to the `Int32` constructor. 
Pre-Fix:
> [Here's a repl.it page with examples.](https://repl.it/@thomasreggi/NODE-2613-without-fix)
```js
> bson.EJSON.parse(`{"$numberInt":"1"}`, { relaxed: false });
Int32 { value: '1' }
> new bson.Int32('1')
Int32 { value: '1' }
```
Post-Fix
> [Here's a repl.it page with the changes from this branch introduced.](https://repl.it/@thomasreggi/NODE-2613-with-fix)
```js
> bson.EJSON.parse(`{"$numberInt":"1"}`, { relaxed: false });
Int32 { value: 1 }
> new bson.Int32('1')
Int32 { value: 1 }
```
[NODE-2613](https://jira.mongodb.org/browse/NODE-2613)
=> [NODE-2613] fix: parseInt value of Int32 in constructor

lib/extended_json.js, test/node/extended_json_tests.js
Since EJSON.stringify is often used as a replacement for built-in JSON.stringify, it would make sense that it would handle the same arguments as JSON.stringify, including primitive values.
Context: here's a place it's being used like JSON.stringify: https://github.com/mixmaxhq/mongo-cursor-pagination/pull/198
=> feat: add support for primitives to EJSON.stringify

.evergreen/install-dependencies.sh
Running `nvm on` in Windows fixes the error: `Failed to replace env in config: ${APPDATA}`
=> chore(ci): turn nvm on in windows

lib/objectid.js
The insufficient validation may otherwise lead to type confusions.
REF: NODE-2618
Signed-off-by: Jakob Ackermann <jakob.ackermann@overleaf.com>
=> fix(object-id): harden the duck-typing

lib/bson/objectid.js
----
The insufficient validation may otherwise lead to type confusions.
REF: NODE-2618
Signed-off-by: Jakob Ackermann <jakob.ackermann@overleaf.com>
=> fix(object-id): harden the duck-typing [backport]

lib/parser/deserializer.js
Edits: "to long" -> "too long", "to short" -> "too short"
=> fix: spelling in deserializer errors

src/bson.ts, src/long.ts, src/parser/deserializer.ts, src/parser/serializer.ts, test/node/extended_json_tests.js
[NODE-2724](https://jira.mongodb.org/browse/NODE-2724)
When comparing the newly exported types from BSON with the community types @types/bson, check for inconsistencies within the driver usage.
```
> mongodb@4.0.0-beta.0 build:ts /Users/thomasreggi/Desktop/git/mongodb/node-mongodb-native
> rimraf lib && tsc
src/bson.ts:32:15 - error TS2305: Module '"../node_modules/@types/bson"' has no exported member 'SerializeOptions'.
32 import type { SerializeOptions } from 'bson';
~~~~~~~~~~~~~~~~
src/bulk/common.ts:604:18 - error TS2339: Property 'checkKeys' does not exist on type '{ ordered: boolean; } & BulkWriteOptions'.
604     finalOptions.checkKeys = false;
~~~~~~~~~
src/bulk/common.ts:997:33 - error TS2339: Property 'checkKeys' does not exist on type 'BulkWriteOptions'.
997       checkKeys: …
```
=> NODE-2724/types-against-driver

README.md, src/parser/deserializer.ts
[NODE-2770](https://jira.mongodb.org/browse/NODE-2770)
PR to remove the `cacheFunctionsCrc32` option from the deserialize function. 
I've checked in a couple different prior tags / branches to see if there was ever an implementation of `crc32`, I only ever saw it set to `null`.
```js
const hash = cacheFunctionsCrc32 && crc32 ? crc32(functionString) : functionString;
```
With it set to null the hashing function would never be called an the hash would only ever be set to the `functionString`.
This deprecates the `crc32` hashing option as, it was never used.
=> NODE-2770/rm-crc32

.nycrc.json, package.json
[NODE-2720](https://jira.mongodb.org/browse/NODE-2720?filter=-1)
This PR fixes NYC coverage. The issue seems to be with the `includes` property within that NYC configuration. Simply removing this property allows the coverage to be reported.
This also adds HTML reporting, for and generates HTML output in the `coverage` folder. Also adds a `coverage:html` npm `script` to `open` the coverage report once it's finished.
=> NODE-2720/coverage

src/long.ts, src/parser/serializer.ts, src/parser/utils.ts, test/node/bigint_tests.js, tsconfig.json
Given JavaScript's new BigInt type the serializer will attempt to fit the value in the smallest possible type. In the following order: Int32, Int64, Decimal128. Any values larger than Decimal128's maximum representable range will result in a thrown TypeError
NODE-2529
There's no logic in here to deserialize to big int only to accept it and serialize it to one of our BSON types. In terms of platform support I only used the BigInt constructor not the `23n` syntax so the code path will just go untravelled on older JS engines.
=> fix: Throw on BigInt type values

src/constants.ts, src/parser/serializer.ts
Numbers that exceed the representable size of int32 will be serialized as doubles to keep consistency with JS VM behavior
NODE-2769
=> refactor: Removes dead code paths from number serialization

src/binary.ts, src/extended_json.ts, src/uuid.ts, test/node/specs/bson-corpus/binary.json
[NODE-2805](https://jira.mongodb.org/browse/NODE-2805?filter=-1)
* Adds in extended JSON parsing for `$uuid`.
* Had a learning curve to understand how UUID's are converted to a binary string for `base64` encoding, until I realized it was a specialized for UUID's.
* Added a couple of UUID helper methods `UUIDPattern`, `parseUUID`, `formatUUID` to a new `uuid.ts` file, some pulled in from the [`uuid` module](https://www.npmjs.com/package/uuid). With the intention on adding the dependency at a later time if necessary.
* Seeking advice on where to put these methods new helper methods (and naming), as we may want to reserve the `uuid.ts` file for the `UUID` class in the future.
* Alternatively could create `UUID` class now and add static `parse` and `format` methods, swappable if we ever use …
=> feat: add extended json parsing for $uuid

api-extractor.json, src/binary.ts, src/bson.ts, src/code.ts, src/constants.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/extended_json.ts, src/int_32.ts, src/long.ts, src/map.ts, src/max_key.ts, src/min_key.ts, src/objectid.ts, src/parser/deserializer.ts, src/parser/serializer.ts, src/regexp.ts, src/symbol.ts, src/timestamp.ts, src/uuid.ts
Also re-enable api-extractor flags to lint our tsdoc blocks.
NODE-2837
=> docs: Add release tags and export symbols from entry point

api-extractor.json
Omit untrimmed definitions file from dist
=> fix: Correct API Extractor config to omit definition file from dist

src/extended_json.ts
NODE-2846
For some reason with the overloads on `stringify` the `d.ts` build was not including the base-level argument types. Because this function has all successive arguments optional AND there's the same return type, there's no reason to have overloads for this function at all.
=> fix: remove stringify overloads

src/objectid.ts, test/node/object_id_tests.js
The previous `Object.defineProperty()` calls did not work because
they did not specify a property descriptor, and even if they had
worked, the signatures of `.inspect()` and `.toString()` would
have mismatched, and even if they weren’t, the result would not
have been very useful as debugging output, because it only returned
the raw hex content of the `ObjectId` and not even e.g. the fact
that this object is an `ObjectId`.
I’m happy with any other solution, but this particular one would
make my life a tiny bit easier :)
Make the `inspect` and `[util.inspect.custom]` methods on `ObjectId` work.
---
Not sure if I should open a JIRA ticket for this, but happy to do so if it helps :)
=> fix: make inspect for ObjectId work

src/binary.ts, src/code.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/int_32.ts, src/long.ts, src/max_key.ts, src/min_key.ts, src/symbol.ts, src/timestamp.ts, test/node/bson_test.js
Adds support for the NodeJS `inspect` function to more BSON data types. This is an upstream change proposed by the mongosh team.
A custom `inspect` function is added for the following data types:
* `Binary`
* `Code`
* `DBRef`
* `Decimal128`
* `Int32`
* `Long`
* `MinKey`
* `MaxKey`
* `BSONSymbol`
* `Timestamp`
=> chore: expand inspect support of BSON types NODE-2875

package-lock.json, package.json, src/bson.ts, src/ensure_buffer.ts, src/parser/serializer.ts, src/parser/utils.ts, test/bson_older_versions_tests.js
The isBuffer check in the buffer module was too strict and led to a failure to deal with older BSON module Binary types. There is now an improved more relaxed method.
NODE-2848
I added testing for this, we can easily expand it to cover more types/cases with older versions of the library.
=> fix: Fix backwards compatibility with older BSON package versions

src/long.ts
When converting the Long code to es6 the alias methods were made into class properties, which makes them enumerable, making debugging statements quite long, this fixes that by making the aliases proper methods.
https://jira.mongodb.org/browse/NODE-2845
=> chore: make Long alias functions into methods

src/bson.ts, src/long.ts, tsconfig.json
fix: remove tslib usage and fix Long method alias
=> fix: remove tslib usage and fix Long method alias

src/binary.ts, src/code.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/int_32.ts, src/long.ts, src/max_key.ts, src/min_key.ts, src/objectid.ts, src/symbol.ts, src/timestamp.ts, test/node/bson_test.js, test/node/object_id_tests.js
Make sure that evaluating the inspection result of a `Binary` object
returns a result that can be evaluated to give an object equivalent
to the original.
=> fix: make inspection result of Binary evaluatable NODE-2947

.eslintignore, rollup.config.js, src/binary.ts, src/code.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/int_32.ts, src/long.ts, src/max_key.ts, src/min_key.ts, src/objectid.ts, src/regexp.ts, src/symbol.ts, src/timestamp.ts, test/node/bson_types_construction_tests.js, tsconfig.json
Reverts a change that upgraded the BSON types to es6 classes
preventing types from being constructed without using new.
NODE-3064
=> fix: permit BSON types to be created without new

src/parser/utils.ts
This PR makes this package usable in a web-worker.
Another approach would be to use `globalThis`. But, that would required node 12+, I see there is quite good support for it in browsers.
=> check both window and self

lib/bson/long.js, lib/bson/parser/serializer.js, test/node/bigint_test.js
Adds helpers toBigInt and fromBigInt to the Long class to help
support 64bit values. Throws an error when `bigint` is attempted to
be serialized.
NODE-2378
=> fix: Throw error on bigint usage and add helpers to Long

src/ensure_buffer.ts, test/node/ensure_buffer_test.js
`instanceof` is notoriously unreliable in JS, because it can
be fooled by prototype manipulation and breaks down entirely
for cross-realm brand checks.
Using `Object.prototype.toString` is generally a better choice
for this.
This also adds `SharedArrayBuffer` as an alternative, as both
should be treated the same under most circumstances.
=> fix: improve ArrayBuffer brand check in ensureBuffer

src/ensure_buffer.ts, src/extended_json.ts, src/parser/calculate_size.ts, src/parser/serializer.ts, src/parser/utils.ts, test/node/extended_json_tests.js
Similarly to 99722f66d, instanceof is not a great brand check in JS
in general, and using `Object.prototype.toString.call()` is better
at detecting built-in types.
This particular change is needed for mongosh, because the user input
it not evaluated in the same `vm.Context` as the bson package that
we’re using.
NODE-3208
=> fix: clean up instanceof usage

src/ensure_buffer.ts, src/objectid.ts, src/parser/serializer.ts, src/parser/utils.ts, src/uuid.ts, test/node/ensure_buffer_test.js
Also fixes NODE-3223 (ensureBuffer ignores byteLength/byteOffset).
This is the "proper" alternative to https://github.com/mongodb/js-bson/pull/418 and matches what e.g. Node.js APIs do.
=> fix: accept Uint8Array where Buffer is accepted

src/parser/deserializer.ts, test/node/bson_test.js
=> fix(NODE-3153): correctly deserialize `__proto__` properties

src/long.ts, test/node/bson_test.js
Do basically the same thing we’re already doing for `Decimal128` to
ensure that the inspect result accurately represents the contents
in a way that can be used to evaluate it again.
NODE-3256
=> fix: make Long inspect result evaluable

src/decimal128.ts, src/long.ts, test/node/bigint_tests.js, test/node/bson_test.js, test/node/bson_types_construction_tests.js, test/node/decimal128_tests.js, test/node/long_tests.js
This adds support for the following constructor signatures:
- `[new] Decimal128(string)`
- `[new] Long(string[, unsigned])`
- `[new] Long(bigint[, unsigned])`
While the first two of these would not have thrown exceptions before,
they would also not have returned any meaningful results, so this
is not a breaking change.
NODE-3264
=> feat: allow Decimal128(string), Long(string), Long(bigint)

test/node/bson_corpus_tests.js
I ran across this one-liner when looking into `Decimal128` usages. (Of course they all were passing since `Decimal.128.fromString` would never be able to deserialize the EJSON, so we now use the EJSON parse helper function, which passes, but aren't false positives)
NODE-3277
=> test: bson corpus spec runner calling wrong fn

test/bson_older_versions_tests.js
This sometimes flakes out for me locally because it takes
slightly longer than the mocha default of 2 seconds to download
the legacy bson zip.
=> chore(test): add timeout to older versions test

src/db_ref.ts, src/extended_json.ts, test/node/specs/bson-corpus/binary.json, test/node/specs/bson-corpus/dbref.json, test/node/specs/bson-corpus/document.json, test/node/specs/bson-corpus/top.json
I wanted to bump the spec tests for NODE-3094, turns out there’s
nothing to do there, but NODE-3247 breaks the tests, so I’ve made
changes that align the handling with the spec here.
=> fix(NODE-3247): bump spec tests and fix up DBRef handling

src/parser/serializer.ts, test/bson_older_versions_tests.js
- Use standard JS methods for copying Buffers, because unlike the
`buffer` module polyfill, these have working typechecking
- Add tests that ensure that for all BSON distributions and all
legacy packages, their serialization is cross-compatible
(modulo NODE-2848, which would require updates to either the
`buffer` poyfill or the legacy 1.x bson versions).
=> fix(NODE-3376): use standard JS methods for copying Buffers

src/extended_json.ts, test/node/extended_json_tests.js
In relaxed mode, non-finite doubles are supposed to be serialized
the same way as in non-relaxed/canonical mode.
=> fix(NODE-3390): serialize non-finite doubles correctly in EJSON

src/timestamp.ts, test/node/bson_test.js, test/node/timestamp_tests.js
Add a `Timestamp({ t: <number>, i: <number> })` overload,
and mark the `Timestamp(low, high)` overload as deprecated.
=> feat(NODE-3504): add unambiguous `Timestamp()` constructor overload

package.json, src/bson.ts, src/parser/deserializer.ts
NODE-3451 documents a performance regression in the node driver v4, which is actually due to a performance regression in js-bson v4 deserialization method (compared to v1).
The notable culprits were:
- Mandatory rewrapping of all input types, even buffer, into a Buffer class via ensureBuffer
- Looping over all string bytes via validateUtf8
- Suboptimal loops over object keys to identify and handle DBRefs
- The entry point `deserialize` method has been updated to check `instanceof Buffer` and skip the rewrapping in those instances; this is a temporary measure that only addresses performance for Node.js buffers
- NOTE: `deserializeStream` was left untouched for scope reasons
- The `deserializeObject` method was updated to check for the presence of potential DBRef keys as …
=> fix(NODE-3451): fix performance regression from v1

package-lock.json
In all the testing to fix the global bug and seeing issues with transient deps the lock file remained unchanged when there were changes to deps.
This doesn't bring in new updates, just reflects the removals.
=> chore: sync lockfile with package dependencies

.gitignore, package-lock.json, package.json, src/binary.ts, src/code.ts, src/db_ref.ts, src/double.ts, src/int_32.ts, src/objectid.ts, src/symbol.ts, src/uuid.ts, test/node/double_tests.js, test/node/int_32_tests.js, test/types/bson.test-d.ts, test/types/tsconfig.json
We have a number of the convenience helpers, toString and toJSON marked as internal on our Type classes. The should be made available in our type definitions. 
Additionally we were missing toString methods for Int32 and Double, I think its unexpected that these would return `[object Object]` for toString. 
I can revert if we want to do this seperately.
=> fix(NODE-3582): fix internal marked APIs, add toString methods to Int32 and Double

src/decimal128.ts, test/node/decimal128_tests.js
Fix a long standing bug in `Decimal128.fromString()`
- https://github.com/mongodb/js-bson/issues/334
- https://jira.mongodb.org/browse/NODE-3021
The `representation` string was wrongly used to find the significant digits. The `digits` array should be used instead.
Note that the v2.0 and v3.0 branches also have this bug.
=> fix(NODE-3021): fix a long standing bug in Decimal128.fromString()

test/node/specs/bson-corpus/document.json, test/node/specs/bson-corpus/regex.json, test/node/specs/bson-corpus/top.json
Adds corpus tests with null bytes in strings, NODE-3447
=> test(NODE-3447): serialization of BSON with embedded null bytes in strings

src/parser/deserializer.ts, test/node/specs/bson-corpus/code.json, test/node/specs/bson-corpus/symbol.json
=> fix(NODE-3493): code and symbol tests are partially testing the wrong types

src/objectid.ts, test/node/object_id_tests.js
Tightens the logic within the ObjectId constructor to make sure that inputs to the constructor are of the proper types, otherwise throws a TypeError. Tests to make sure that invalid inputs have an error thrown (rather than creating a "broken" ObjectId object with no 'id' property, for instance) are added.
=> fix(NODE-3662): error checking to make sure that ObjectId results in object with correct properties

src/ensure_buffer.ts, src/error.ts, src/objectid.ts, test/binary_parser.js, test/node/bigint_tests.js, test/node/bson_corpus_tests.js, test/node/bson_test.js, test/node/ensure_buffer_test.js, test/node/error_test.js, test/node/object_id_tests.js, test/node/uuid_tests.js, test/register-bson.js
Fixes the constructors for BSONTypeError and TypeError with Object.setPrototypeOf so that instanceof checks pass with both error types. The assertion override for `throw` in `register-bson.ts` is removed since it is no longer necessary with the fix. Tests making sure the errors respond properly to instanceof checks, show up with the correct names in the stack trace, and pass in input error messages correctly are added.
=> fix(Node 3724): Fix BSONTypeError and BSONError to correctly handle instanceof checks

src/ensure_buffer.ts, src/error.ts, src/objectid.ts, test/binary_parser.js, test/node/bigint_tests.js, test/node/bson_corpus_tests.js, test/node/bson_test.js, test/node/ensure_buffer_test.js, test/node/error_test.js, test/node/object_id_tests.js, test/node/uuid_tests.js, test/register-bson.js
Fixes the constructors for BSONTypeError and TypeError with Object.setPrototypeOf so that instanceof checks pass with both error types. The assertion override for `throw` in `register-bson.ts` is removed since it is no longer necessary with the fix. Tests making sure the errors respond properly to instanceof checks, show up with the correct names in the stack trace, and pass in input error messages correctly are added.
=> fix(NODE-3724): Fix BSONTypeError and BSONError to correctly handle instanceof checks

package-lock.json, package.json, src/parser/deserializer.ts, test/node/tools/utils.js, test/node/utf8_tests.js, test/types/deserialize.test-d.ts
Adds a new validation option in DeserializeOptions that allows all or a specific subset of top-level keys in a document to be excluded from strict utf-8 validation and instead applies the replacement character behavior. Tests are added to make sure that both global and specific-key subsets can have utf8 validation enabled and disabled. 
Default behavior is to have strict utf-8 validation (an error will be thrown if invalid utf8 is detected). This change gives users the ability to opt into character replacement behavior instead of strict utf-8 validation.
=> feat(NODE-3740): Implement root and top level key utf-8 validation settings for BSON

package-lock.json, src/objectid.ts, test/mocha.opts, test/node/object_id_tests.js
adds validation for string and byte length matching for new ObjectID's.
bugs found with strings of char-length 12, but byte-length =/= 12.
=> fix(NODE-3760): ObjectId.isValid string and byte length match

src/parser/calculate_size.ts, src/parser/serializer.ts, test/node/to_bson_test.js
In the serializer, when it comes to check for an override value (`toBSON`), changing  the `value` check to compare with `null` and `undefined` instead of relying on the truthiness of `value`.
Cannot extend BigInt prototype with`.toBSON()` since `0n === false`
trying to make this work
```ts
BigInt.prototype.toBSON = function() {
return Long.fromBits(Number(this.valueOf() & BigInt(0xffffffff)),
Number(this.valueOf() >> BigInt(32)))
}
// src/parser/serializer.ts:769
// Is there an override value
if(value && value.toBSON){
// this won't go through if value === 0n
...
}
...
// then trows error here since value hasn't been overidden
// src/parser/serializer.ts:779
else if (typeof value === 'bigint') {
throw new BSONTypeError('Unsupported type BigInt, please use Decimal128');
}
```
=> fix(NODE-3821): nullish check before using toBSON override function

src/objectid.ts, test/node/object_id_tests.js, test/node/tools/utils.js
This is a PR based on #287 by @siboulet but for the new typescript codebase.
I used the following benchmark:
```javascript
const ObjectId = require("./lib/objectid").ObjectId;
const data = [];
const id = new ObjectId().toString();
const lastId = new ObjectId();
const runs = 1000000;
for (let i = 1; i < runs; i++) {
data.push(new ObjectId());
}
data.push(lastId);
const results = [];
function runFilter(name, cb) {
const now = Date.now();
let length = data.filter(cb).length;
results.push({ name, length, time: Date.now() - now });
}
console.log(`Running tests on ${data.length} ids array`);
runFilter("Filter toString to string", s => s.toString() === id);
runFilter("Filter toStringBoth", s => s.toString() === lastId.toString());
runFilter("Filter String() Both", s => String(s) === …
```
=> fix(NODE-3015): ObjectId.equals should use Buffer.equals for better performance

package-lock.json, src/objectid.ts, test/node/type_identifier_tests.js, test/types/bson.test-d.ts
The type information for ObjectId._bsontype had the wrong capitalization. Runtime value is still correct.
Also added runtime and type tests to prevent regressions.
It's a bug 🐛
=> fix(NODE-3962): correct type for ObjectiId._bsontype

.evergreen/install-dependencies.sh
Update setup scripts, aligning with our other repos
Buggy behavior on old systems
- [N/A] Changes are covered by tests
- [N/A] New TODOs have a related JIRA ticket
=> chore: update nvm environment setup

src/objectid.ts
The error message when creating a new `ObjectId()` object with bad parameter.
https://jira.mongodb.org/browse/MONGOSH-1155
=> fix(MONGOSH-1155): update error message in ObjectId class

package-lock.json, package.json
- downlevel-dts is bumped to the newest version
- a `typesVersion` is added to the package.json, so users on newer versions of TS are not using the output of downlevel-dts
No.
=> chore: add typesversion to package.json && bump downlevel-dts version

src/binary.ts, src/code.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/int_32.ts, src/long.ts, src/map.ts, src/max_key.ts, src/min_key.ts, src/objectid.ts, src/regexp.ts, src/symbol.ts, src/timestamp.ts, tsdoc.json
https://jira.mongodb.org/browse/NODE-4158
=> docs(NODE-4158): Annotate BSON classes with a category

package-lock.json, package.json, rollup.config.js, src/parser/utils.ts
This adds the `@rollup/plugin-replace` plugin, which is used to set a `process.browser` variable, to allow Rollup to create different builds for Node.js and browsers.
The check for `process.browser` was added to the `detectRandomBytes` function, which should now only require `crypto` in the js bundle, when `process.browser` was set to false while Rollup was running.
I don't think so.
The issue fixed by this change is described over here: https://jira.mongodb.org/browse/NODE-4211
```
WARNING in ./node_modules/bson/dist/bson.browser.esm.js 2196:26-55
Module not found: Error: Can't resolve 'crypto' in '/Users/rvanmil/Development/ctac-web-app-e2e-monitoring/node_modules/bson/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the …
```
=> fix(NODE-4211): Do not require crypto in browser builds

.evergreen/config.yml, .evergreen/init-nvm.sh, .evergreen/install-dependencies.sh, .evergreen/run-typescript.sh, package-lock.json, package.json
Remove downlevel-dts and test public types / compiling src against old/current/next TS versions
oldest version is set to TS v4.0.2 (there is no 4.0.0)
downlevel-dts isn't providing any needed changes to the types
=> fix(NODE-4302): remove downlevel ts and typesVersions

etc/benchmarks/lib_runner.mjs, etc/benchmarks/main.mjs
Make the script test bson-ext and move out the import logic
=> chore: add bson-ext to benchmark tool

src/binary.ts
Adds a note that Binary(string) is probably not what you want unless you really know what you’re doing.
(This was inspired by old Compass code getting this wrong in at least one place.)
This is a doc change.
=> docs(NODE-4349): add note about Binary(string) behavior

src/extended_json.ts, test/node/bson_test.js, test/node/extended_json_tests.js
Similar fix and similar test as f34cabc31e66, just for
EJSON serialization instead of BSON deserialization.
No.
Aligning behavior with regular JSON.
=> fix(NODE-4381): handle `__proto__` well in EJSON

src/bson.ts, tsconfig.json
compiling `js-bson` with `isolatedModules` set to `true`
no, as per https://www.typescriptlang.org/tsconfig#isolatedModules the behaviour of the code does not change
I'm working on a feature complete port of `js-bson` for deno. Idea is to "compile" this library automatically for deno, into `bson-deno`
Current state of `bson-deno` can be reviewed here: https://github.com/thekorn/bson-deno
The "build" script is maintained in this repository: https://github.com/thekorn/deno-build-mongodb-native
The overall goal is to provide an up-to-date, feature complete version of the mongodb-native client library for deno
For tracking purposes I also created a jira ticket: https://jira.mongodb.org/browse/NODE-4401
=> chore(NODE-4401): enable isolatedModules tsc compiler option

.evergreen/config.yml, .evergreen/init-nvm.sh, .evergreen/install-dependencies.sh, .evergreen/run-tests.sh, test/bson_older_versions_tests.js
Deleting windows tests from evergreen. 
Evergreen no longer tests on Windows.
There is no new documentation needed for these changes.
The CI fails on windows since it can't properly setup nvm, which is unrelated to js-bson. Since node is consistent across all OS, there is no need to test on multiple OS.
=> test(NODE-4357): delete windows tests

src/parser/serializer.ts, test/node/uuid_tests.js
BSON.serialize() now supports new BSON.UUID() as input directly, users don't need to call new BSON.UUID().toBinary(), while that option is still supported.
Yes, we'll need to add that uuid: new BSON.UUID() is a valid input to BSON.serialize
This is part of a larger project looking to better integrate the UUID type into BSON.
There are three new use cases possible:
| Type  | Example |
| ------------- | ------------- | 
| Object |  BSON.serialize({ uuid: new BSON.UUID() });  |
| Map | BSON.serialize(new Map([['uuid', new BSON.UUID()]])); | 
| Array  | BSON.serialize({ uuid: [new BSON.UUID()] });  | 
*Note, we can also have multiple UUIDs passed in at once for all cases. For example, BSON.serialize({ uuid: new BSON.UUID(), uuid2: new BSON.UUID() });
=> feat(NODE-4405): support serializing UUID class

package-lock.json, package.json, src/parser/deserializer.ts, test/node/uuid_tests.js, test/register-bson.js
When deserializing a UUID object, the user can use the boolean option ```promoteUUIDs``` to return an object of type UUID. This is part of an ongoing project to better integrate the use of the UUID class into js-bson.
There is a new option ```promoteUUIDs``` available to users when deserializing objections.
If the existing object is of the UUID subtype, and the flag is true (ex: ```{promoteUUIDs: true}```), then the resulting deserialization will return a UUID object. If the flag is false, or omitted it will return a binary object.
After deserializing, users can now have UUID objects.
=> feat(NODE-4419): UUID class deserialization

.evergreen/config.yml, package-lock.json, package.json, test/mocha.opts, test/register-bson.js
- a new task is added to CI that runs our tests on Node18
- tasks now run on ubuntu20
- @types/node is bumped to the latest version to resolve a Typescript failure (on typescript@next)
- register-expect was removed in favor of registering expect globally ourselves.   it's been a while since I made the change but it was necessary to fix a CI failure when I upgraded to Node18 or ubuntu20
No.
=> ci(NODE-4655): add 18 to CI matrix

.gitignore, etc/benchmarks/lib_runner.mjs, etc/benchmarks/main.mjs, package-lock.json, package.json
There's still some cruft in here, but its intentional in case someone else want to pull it down and check my work.
The issue reported does reproduce but only when we try to simulate parallelism. I don't think it is the parallelism that effects our BSON library it just offers enough load to be able to measure the difference. 
The goal here isn't to fix anything but some hypothesis, some ruled out:
- getValidatedString moved the buffer.toString to a helper, undoing this did not demonstrate a change
- removing all the UTF8 key validation logic may have introduced overhead of allocating a Set, checking has etc.
- removing it did not appear to have an impact
- The analysis that I would recommend in a follow up is taking a close look at globals / new structures added to deserializeObject that …
=> perf(NODE-4726): bench many strings in large batch in parallel

docs/upgrade-to-v5.md, rollup.config.mjs, src/binary.ts, src/code.ts, src/db_ref.ts, src/decimal128.ts, src/double.ts, src/error.ts, src/int_32.ts, src/long.ts, src/max_key.ts, src/min_key.ts, src/objectid.ts, src/regexp.ts, src/symbol.ts, src/timestamp.ts, test/node/bson_types_construction_tests.js, test/node/type_identifier_tests.js, tsconfig.json
Bump TS target from es5 to es2020. Fixes related to syntax changes.
Yes, see migration guide updates.
Modern syntax allows for better control over what we publish (class sytax adds error handling for constructors etc.)
=> feat!(NODE-4440): bump TS target version to es2020

docs/upgrade-to-v5.md
Improving the docs, follow up for #518
=> docs(NODE-4804): Improve migration guide notes

docs/upgrade-to-v5.md, src/parser/deserializer.ts, test/node/decimal128_tests.js
Remove toObject transformer for d128
Difficult maintenance, and unexpected results from serializer when defined (toObject's return type isn't constrained)
=> feat!(NODE-4461): remove Decimal128 toObject transformer

docs/upgrade-to-v5.md, src/objectid.ts, src/parser/utils.ts, test/node/object_id_tests.js
Removing deprecated ObjectId methods.
Methods are deprecated, alternatives exist.
=> feat!(NODE-4704): remove deprecated ObjectId methods

docs/upgrade-to-v5.md
- Making a note in the migration guide
- this commit will add to the changelog
- Bug was fixed in #518
We want the bug to appear in the changelog.
=> fix(NODE-4771): serializeFunctions breaks function names outside of basic latin

README.md, docs/upgrade-to-v5.md
Update guide about bundle changes
Update readme examples about importing and using with bundlers
Follow up to #534 
=> docs(NODE-4901): update guide about bundle changes

src/double.ts, test/mocha.opts, test/node/bson_corpus.spec.test.js, test/node/double_tests.js, test/register-bson.js
Same as #548, this is a backport
=> fix(NODE-4905): double precision accuracy in canonical EJSON

README.md, package.json
Add react-native exports specifier.
Set it to the commonjs bundle.
Document polyfills.
To support react native.
=> feat(NODE-4927): exports in package.json for react native and document how to polyfill for BSON

src/parser/serializer.ts, test/node/to_bson_test.js
Adding fix to ensure that values of `Map`s run are replaced by the result of calling their `toBSON` method if it exists.
No
Ensure that `BSON.serialize` keeps with spec behaviour
=> fix(NODE-4887): serializeInto does not check for the presence of a toBSON method for values in Map entries

src/double.ts, test/node/bson_corpus.spec.test.js, test/node/double_tests.js
Removes the logic for integer-like doubles
Fixes an output incompatibility with other languages
=> fix(NODE-4932): remove .0 suffix from double extended json values

src/extended_json.ts, test/node/bigint.test.ts, test/node/extended_json.test.ts
Adding capability to stringify BigInt
No
Allow users to make use of native Javascript `BigInt`s instead of `BSON.Long`
=> feat(NODE-4873): support EJSON stringify from BigInt to $numberLong

package.json
This helps resolve Compass-specific bundling headaches.
=> chore(NODE-5057): add compass:exports fields to package.json

src/bson.ts, src/error.ts, src/extended_json.ts, test/node/error.test.ts, test/node/exports.test.ts, test/node/extended_json.test.ts
`EJSON.parse` fails to correctly deserialize cEJSON strings which contain date fields.
- `EJSON.parse` now correctly deserializes cEJSON dates
- Added new `BSONError` subclass, `BSONRuntimeError` to cover internal failures
No
=> fix(NODE-5056): EJSON.parse date handling when useBigInt64=true

package.json, test/node/exports.test.ts
- Updated the package.json to make the typedefs available for mjs users
- Added a test that will prevent the order of keys from changing
- I verified locally with my reproduction that the type defs are picked up now
TS defs don't show up for module: node16/nodeNext TS users
=> fix(NODE-5025): no type definitions for es module

.evergreen/config.yml, .evergreen/run-bundling-test.sh, README.md, etc/rollup/rollup-plugin-require-rewriter/require_rewriter.mjs, src/utils/node_byte_utils.ts, test/bundling/webpack/.gitignore, test/bundling/webpack/install_bson.cjs, test/bundling/webpack/package.json, test/bundling/webpack/readme.md, test/bundling/webpack/src/index.ts, test/bundling/webpack/tsconfig.json, test/bundling/webpack/webpack.config.js
- Remove 'node:' from crypto import
- Change rollup plugin to also remove 'node:'
- Added an example webpack config bundling bson
- New evergreen task: 
- takes the current bson src
- runs rollup and npm pack to get a tgz of lib
- installs the tgz as a dependency of the webpack project
- tries to build using webpack
- Added webpack documentation to readme.md
It may not be immediately clear what the workarounds are for making webpack compatible with BSON. So we're now integration testing and documenting the expected path.
=> fix(NODE-5048): webpack unable to bundle import with leading 'node:'

docs/upgrade-to-v5.md
Mention the class syntax "new" requirement
Clarity on a v5 breaking change
=> docs(NODE-5080): add a note about class syntax

etc/clean_definition_files.cjs, package-lock.json, package.json, test/node/release.test.ts
- Add definition clean up script from driver
- Add file list validation from FLE
Clean extraneous files
=> chore(NODE-5277): add definition clean up script

.eslintrc.json, package-lock.json, package.json, rollup.config.mjs, src/bson.ts, src/parser/deserializer.ts, src/timestamp.ts, tsconfig.json
Updates the driver to use Typescript 5.
- Updates typescript to ^5.0.4
- Updates api-extractor to ^7.35.1 (to use typescript 5)
- All other typescript dependencies were already further along than the minimum.
- Removes the `importsNotUsedAsValues` config and replaces with eslint rule.
- Updates all the files to adhere to new eslint rule.
- Fixes the number comparison between `number` and `Int32`.
None
NODE-5324
=> chore(NODE-5324): update to typescript 5

.github/workflows/release.yml
Add id-token permission for releasing
Needed for releases
=> chore(NODE-5435): add id-token permission to release workflow

src/binary.ts
Removes the deprecated `UUID.cacheHexString`.
Removes the deprecated `UUID.cacheHexString`
None
NODE-5223
=> feat(NODE-5223)!: remove deprecated cacheHexString

.github/workflows/release.yml
Move permissions, make release work again
No
=> chore(NODE-5475): move id-token permission to workflow

src/binary.ts, test/node/bson_node_only_tests.js, test/node/bson_types_construction_tests.js, test/node/extended_json.test.ts, test/node/test_full_bson.js
- Removes legacy ISO-8859-1 format from Binary `constructor`, `.write`, and `.value` methods
No
- Unusual string format, see highlight
The `Binary` BSON type no longer accepts a string as a constructor argument nor can `write()` be invoked with a string argument. Both methods interpreted strings as binary sequences rather than UTF-8 or base64 which are much more common and expected formats. If there is a string representation of your data it is now expected that the logic that interprets the string format exists outside the Binary class to avoid misinterpreting data.
```ts
new Binary(Buffer.from('ÿÿ', 'binary'));
// Binary.createFromBase64("//8=", 0)
new Binary(Buffer.from('ÿÿ', 'utf8'));
// Binary.createFromBase64("w7/Dvw==", 0)
new BSON.Binary(Buffer.from('AAAA', 'base64'))
// …
```
=> feat(NODE-4769)!: remove ISO-8859-1 string support from Binary

package-lock.json, package.json, src/objectid.ts, src/utils/byte_utils.ts, test/node/bson_test.js, test/node/object_id.test.ts
- Removing the ability to pass a string that reports a length of 12 from creating an ObjectId
- Updating the .equals method to correspond
The usage was never reported by the API prior and worked inconsistently, 12 length strings interpreted as utf8 /  iso88591 interchangeably. I think this release note serves as enough documentation. 
See notes, and doc section.
> (From [String.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length)): [The String length] property returns the number of code units in the string. JavaScript uses [UTF-16](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters) encoding, where each Unicode character may be encoded as one …
=> feat(NODE-4770)!: remove 12 length string support from ObjectId constructor

README.md
NODE-5525
Added table with version compat info for the nodejs driver
This is documentation
Clarity about add-on compatibility
- [N/A] Ran `npm run check:lint` script
- [N/A] Changes are covered by tests
- [N/A] New TODOs have a related JIRA ticket
=> docs(NODE-5525): add nodejs driver version compat table

.github/scripts/highlights.mjs, .github/scripts/pr_list.mjs
- Use a Set to remove duplicate PR numbers
- Add a log for the entire length of the highlight
- https://github.com/mongodb/node-mongodb-native/pull/3816
No
Dedupe release notes.
=> chore(NODE-5543): fix duplicate PR highlights

src/code.ts, src/symbol.ts, test/node/code.test.ts, test/node/symbol.test.ts
Accounts for quotes (and other characters that need escaping) when printing Code() or BSONSymbol() inspect output.
No.
https://jira.mongodb.org/browse/NODE-5559
=> fix(NODE-5559): account for quotes when inspecting Code and BSONSymbol

.github/workflows/release-alpha.yml
Pull in release-alpha workflow from driver codebase
No
NODE-5580
N/A
=> chore(NODE-5580): add release alpha action

.evergreen/config.yml, .evergreen/install-dependencies.sh
Fixes Node 16 failures with npm 10.
- Installs npm@9 when on Node 16 or lower.
None
NODE-5603
=> test(NODE-5603): use npm 9 on eol node versions

src/decimal128.ts, test/node/decimal128.test.ts, test/node/decimal128_tests.js
- Adds `Decimal128.fromStringWithRounding` static method
- Convert `test/node/decimal128_tests.js` to typescript and add tests for `fromStringWithRounding`
- Yes, DOCSP ticket will be filed
NODE-5594
Prior to the 6.0.0 release, `Decimal128.fromString` performed rounding behaviour by default that rounded numbers with >34 significant digits incorrectly. In addition to this bug, the intention of the `Decimal128` type and specification is to provide an interface to a high-precision floating point value, so rounding by default also went against this intention, which is why that behaviour was removed from the method in the 6.0.0 release.
We understand that some users may have come to rely on the rounding behaviour, so that has been corrected here and exposed via a new static method, …
=> feat(NODE-5594): add Decimal128.fromStringWithRounding() static method

.github/workflows/release-5.x.yml, .gitignore
- Adds release automation for 5.x branch
- add benchmarks.json to gitignore
No
Release automation for 5.x
=> chore: add 5.x release workflow

.github/scripts/highlights.mjs, .github/scripts/pr_list.mjs, .github/workflows/release-5.x.yml, .github/workflows/release-alpha.yml
- A clean sync of all the scripts and flows on main back to 5.x
- `git restore -s chore-5x-release -SW -- .github`
No
When the highlights task runs, it will use the scripts on this branch
=> chore: backport release scripting to 5.x branch

src/error.ts
- Change `BSONVersionError` to say MAJOR.x.x instead of MAJOR.0 or later
No
Previously our BSONVersionError when thrown stated that the "bson type must be from 6.0 or later" our intention is to prevent cross major bson types from reaching the serialization logic as breaking changes to the types could lead to silent incompatibilities in the serialization process. We've updated the message to make that intention clear: "bson types must be from bson 6.x.x"
=> fix(NODE-5640): BsonVersionError improve message clarity

src/error.ts
- Change `BSONVersionError` to say MAJOR.x.x instead of MAJOR.0 or later
No
Previously our BSONVersionError when thrown stated that the "bson type must be from 5.0 or later" our intention is to prevent cross major bson types from reaching the serialization logic as breaking changes to the types could lead to silent incompatibilities in the serialization process. We've updated the message to make that intention clear: "bson types must be from bson 5.x.x"
=> fix(NODE-5641): BsonVersionError improve message clarity

.evergreen/config.yml
Move the `NPM_VERSION` var to the install dependencies task
No.
Make sure node 14 installs the right version of npm
=> chore(NODE-5547): fix npm version setting var

.evergreen/config.yml, .evergreen/init-node-and-npm-env.sh, .evergreen/init-nvm.sh, .evergreen/install-dependencies.sh, .evergreen/run-checks.sh, .evergreen/run-tests.sh, .evergreen/run-typescript.sh, package-lock.json, package.json
- Remove nvm and backport node download script from other repos
- backports init-node-and-npm-env.sh in place of init-nvm
- backports install-dependencies script.
- Remove `--continue-at -` flag, older node versions unable to be downloaded with this set
- exempt node 6 from upgrading its npm version, npm 3 is unable to install a newer npm version
- bump `@types/node` to fix a typescript@next compilation failure
No
Fix BSON 4.x setup failures to make it usable for testing
=> chore(NODE-5547): fix BSON 4.x CI

.github/workflows/release_notes.yml
A comment "run release_notes" from an admin will now trigger the release notes automation. The workflow dispatch also works.
Will update the release instructions document.
Commenting on the release PR is a more convenient UX than the workflow dispatch. This also removes the need to select the branch from that pane as we checkout the ref based on PR number.
=> chore(NODE-5768): add comment trigger for release notes

src/objectid.ts, test/types/bson.test-d.ts
Deprecate `number` as an input to `ObjectId` constructor.
Create separate overloads for each input type of the ObjectID constructor and deprecate one that accepts a numeric input value.
None
[NODE-3034](https://jira.mongodb.org/browse/NODE-3034)
Instead, use `static createFromTime()` to set a numeric value for the new ObjectId.
=> feat(NODE-3034): deprecate number as an input to ObjectId constructor

rollup.config.mjs, src/binary.ts, src/error.ts, src/parser/deserializer.ts, src/utils/byte_utils.ts, src/utils/latin.ts, src/utils/node_byte_utils.ts, src/utils/web_byte_utils.ts, test/node/byte_utils.test.ts, test/node/release.test.ts, test/node/utils/latin.test.ts, tsconfig.json
- BSON's UTF8 parsing logic will attempt to use `String.fromCharCode` if bytes are under 128
- Move UTF8 validation after attempting the above, if bytes are below 128 there is nothing to validate
- No
This has shown to have much better performance for strings that fit in the basic latin range. Quite often this is BSON keys.
The BSON library's string decoding logic now attempts to optimize for basic latin (ASCII) characters. This will apply to both BSON keys and BSON values that are or contain strings. If strings are less than 6 bytes we observed approximately ~100% increase in speed while around 15 bytes the performance was about ~30% better. For any non-basic latin bytes or at 20 bytes or greater the BSON library will continue to use Node.js' Buffer.toString API.
The intent is to …
=> feat(NODE-5861): optimize parsing basic latin strings

test/bench/etc/run_granular_benchmarks.js
Replaced hardcoded reference to `bson#main` when running pre-benchmark setup for `run_granular_benchmarks.js`
No
NODE-5922
=> test(NODE-5922): replace hardcoded reference to bson#main

src/utils/byte_utils.ts, src/utils/latin.ts, src/utils/node_byte_utils.ts, src/utils/web_byte_utils.ts, test/node/byte_utils.test.ts, test/node/utils/latin.test.ts
This is the inverse opimization made in: https://github.com/mongodb/js-bson/pull/642
Should have thought of it sooner :)
- Removed fromUTF8 dead code, we always call encodeInto which is BYOB (bring your own buffer 🍻)
No
When strings are short and are only basic latin, it is faster to iterate length of the string and call charCodeAt to obtain the UTF8 byte value.
The BSON library's string encoding logic now attempts to optimize for basic latin (ASCII) characters. This will apply to both BSON keys and BSON values that are or contain strings. If strings are less than 6 bytes we observed approximately 100% increase in speed while around 24 bytes the performance was about 33% better. For any non-basic latin bytes or at 25 bytes or greater the BSON library will continue to use Node.js' …
=> feat(NODE-5909): optimize writing basic latin strings

src/objectid.ts, src/parser/serializer.ts, test/node/object_id.test.ts
- For small byte sequences copy the values "manually" rather than using TypedArray.set
No.
- `TypedArray.set` can be slower than just running a for loop or manually assigning bytes into the array for copies of 16 bytes or less. 
- ObjectIds are 12 bytes, UUIDs are 16, and decimal128 values are 16 bytes.
[benchmarks](https://docs.google.com/spreadsheets/d/1gRaiQGJYDnxh4TRn6HNm0KxBQkyEZBAmKEeGEPXJpuI/edit#gid=1025312026)
When serializing ObjectIds, Decimal128, and UUID values we can get better performance by writing the byte-copying logic in Javascript for loops rather than using the TypedArray.set API. ObjectId serialization performance is 1.5x-2x faster.
=> perf(NODE-5910): optimize small byte copies

src/bson.ts, src/objectid.ts, src/parser/deserializer.ts, src/parser/serializer.ts, src/utils/number_utils.ts, test/node/release.test.ts
Add number bytewise get and set utils
No
- Instead of repeating bit shifting work throughout the serializer and deserializer we can consolidate the operations to helper utils that work across web and node
- These utils employ bit shifting operations which are more performant than using a DataView
=> perf: refactor bit operations into helper functions

.eslintrc.json, src/bson.ts, src/objectid.ts, src/parser/deserializer.ts, src/parser/serializer.ts, src/utils/byte_utils.ts, src/utils/number_utils.ts, src/utils/web_byte_utils.ts, test/node/bigint.test.ts, test/node/release.test.ts, test/node/utils/number_utils.test.ts
- Removes all usage of dataview in favor of Float64Arrays and bit math
We keep a Float64Array and a Uint8Array referencing the same ArrayBuffer. With 8 lines worth of assignment we can take the bytes from input BSON and put them into the Uint8Array and use the Float64Array to interpret them as a LE double.
For bigints we can shift the value into two 32 bit components and use javascript's truncation logic to pull out the bytes as we shift down to each segment of the number.  
No
Creating data views has an impact on peformance, and we can easily avoid using it altogether. Generally, we see better performance the more logic we code in JavaScript.
Benchmarks See below
We now use bit shifting and multiplication operators in place of DataView getX/setX calls to parse and serialize bigints and a …
=> perf(NODE-5934): replace DataView uses with bit math

src/bson.ts, src/decimal128.ts, src/objectid.ts, src/parser/deserializer.ts, src/utils/byte_utils.ts, src/utils/node_byte_utils.ts, src/utils/web_byte_utils.ts
Use allocUnsafe which uses Node.js' pool of pre-allocated memory and does not santize it before returning it to the caller. We can use it in cases where we overwrite the entire returned Buffer to improve the performance of creating small memory allocations for ObjectIds and Decimal128 instances.
No.
Using the memory pool is faster than creating a new allocation.
For small allocations Node.js performance can be improved by using pre-allocated pooled memory. ObjectIds and Decimal128 instance will now use allocUnsafe on Node.js.
=> perf(NODE-5955): use pooled memory when possible

src/binary.ts, src/constants.ts, test/node/constants.test.ts, test/node/specs/bson-corpus/binary.json
New `BSON.Binary` subtype 0x08 `sensitive` is introduced.
See release highlights.
No,  internal changes only.
- Required by downstream teams (shell).
- Sensitive = excluded from logging, creating more security for sensitive values like HMAC keys. 
When a BSON.Binary object is of 'sensitive' subtype, the object's subtype will equal `0x08`.
=> feat(NODE-5506): add Binary subtype sensitive

.evergreen/config.yml, src/utils/number_utils.ts, test/node/double.test.ts, test/node/utils/number_utils.test.ts
Flipped the order we parse bytes from the float array depending on platform endianness
No.
Floats will not serialize or deserialize correctly on big endian systems
A recent change to the BSON library started parsing and serializing floats using a `Float64Array`. When reading the bytes from this array the ordering is dependent on the platform it is running on and we now account for that ordering.
=> fix(NODE-6016): flip byte order depending on system endianness

.evergreen/config.yml, .evergreen/run-big-endian-test.sh, test/s390x/big_endian.test.ts
- Add a zSeries task that specifically runs the big endian test
- Temporary solution to make sure our change actually fixes the bug and no further regressions
No.
- Inspect what we expect
=> test(NODE-6017): add an s390x big endian test

.eslintrc.json, src/bson.ts, src/parser/on_demand/index.ts, src/parser/on_demand/parse_to_elements.ts, src/parser/on_demand/parse_to_structure.ts, test/node/parser/on_demand/parse_to_structure.test.ts, test/node/release.test.ts, test/node/tools/utils.js
- Added an API that will iterate embedded document structures in BSON
No.
To encapsulate the complexity of iterating into nested structures such that one can write a function responsible for reviving each BSON value as needed and decide whether or not to create a nested structure.
=> feat(NODE-5958): add BSON iterating API

src/parser/on_demand/index.ts, src/parser/on_demand/parse_to_elements.ts, src/utils/byte_utils.ts, src/utils/number_utils.ts
- Adds utf and number parsing utils to onDemand
No
A reviver will be receiving offsets into a BSON byte sequence and will need to interpret them at JS values. These utilities provide what we need without rewriting the logic they already implement. We do not necessarily need these to be part of the final API, the driver works on Node.js so we do not need the logic for switching between web and node. We also probably only need a subset of these functions as mentioned above, for example, toHex is for display purposes and likely does not have a use for what we aim to do with this API.
=> feat(NODE-5959): make byte parsing utils available on onDemand library

src/binary.ts, test/node/binary.test.ts
`Binary.toString` and `Binary.toJSON` now respect position when printing out binary object.
See release highlights.
No.
Bug Fix.
When the `toString()` or `toJSON` method is called on a `Binary` instance, it will print out until the instance's position property of the object, instead of the entire buffer.
Example:
```typescript
new BSON.Binary().toString();
// old output: '\x00\x00\x00\x00...' (256 zeros)
// new output:  ' ' 
```
=> fix(NODE-6042): Binary.toString output with respect to position

src/int_32.ts, test/node/int_32_tests.js
Add static `Int32.fromString()` method.
Yes, there are new API docs.
NODE-3660 user ticket, our validation in the Int32 is lacking. In V7, we will add `Int32.fromString(value)` validation call into the `Int32` constructor's `string` case.
This method attempts to create an `Int32` type from string, and will throw a `BSONError` on any string input that is not representable as an `Int32`.
Notably, this method will also throw on the following string formats:
- Strings in non-decimal formats (exponent notation, binary, hex, or octal digits)
- Strings with non-numeric and non-leading sign characters (ex: '2.0', '24,000')
- Strings with leading and/or trailing whitespace
Strings with leading zeros, however, are allowed
=> feat(NODE-6087): add Int32.fromString method

src/double.ts, test/node/double.test.ts
Add static `Double.fromString()` method.
Yes, there are new API docs.
NODE-3660 user ticket, our validation in the Double is lacking. In V7, we will add `Double.fromString(value)` validation call into the `Double` constructor's `string` case.
This method attempts to create an `Double` type from a string, and will throw a `BSONError` on any string input that is not representable as a `IEEE-754 64-bit double`.
Notably, this method will also throw on the following string formats:
- Strings in non-decimal formats (exponent notation, binary, hex, or octal digits)
- Strings with characters other than sign, numeric, floating point, or slash characters (Note: `'Infinity'`, `'-Infinity'`, and `'NaN'` input strings are still allowed)
- Strings with leading and/or trailing whitespace
Strings with …
=> feat(NODE-6086): add Double.fromString() method

src/double.ts, test/node/double.test.ts
`Double.fromString` should allow `'+'` character in its input. 
`Double.fromString` should allow exponential format.
See above.  and also refactor some of the function to make the error messages more clear and the code's logic clearer as well. 
No, bug fix on an unreleased feature.
See description.
=> fix(NODE-6102): Double.fromString prohibiting '+' character and prohibiting exponential notation

etc/rollup/rollup-plugin-require-vendor/require_vendor.mjs, src/parse_utf8.ts, src/parser/deserializer.ts, src/utils/node_byte_utils.ts, src/utils/web_byte_utils.ts, src/validate_utf8.ts, test/node/byte_utils.test.ts, test/node/data/utf8_wpt_error_cases.ts, test/node/parser/deserializer.test.ts, test/node/release.test.ts
Outside of web, our `toUtf8` function was insufficiently strict and allowed overlong encodings. 
Change our functionality to use  js`TextDecoder` to double check utf8 input when a replacement character is detected. 
No.
Drivers wide initiative to make UTF-8 validation strict and consistent. 
Specifically, this affects `deserialize` when utf8 validation is enabled, which is the default.
An overlong encoding is when the number of bytes in an encoding is inflated by padding the code point with leading 0s ([see here for more information](https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings)).
=> fix(NODE-6123): utf8 validation is insufficiently strict

src/long.ts, test/node/long.test.ts, test/node/parser/deserializer.test.ts
`Long.fromString` no longer coerces the following cases to `Long.ZERO` when the provided radix supports all characters in the string:
- `'+Infinity'`, `'-Infinity'`, or `'Infinity'` when 35 <= radix  <= 36
- `'NaN'` when 24 <= radix  <= 36
``` typescript
// when writing in radix 27, 'n' and 'a' are valid characters, so 'NaN' represents the decimal number 17060
Long.fromString('NaN', 27); // new Long(17060)
Long.fromString('NaN', 10); // new Long(0) <-- Since 'NaN' is not a valid input in base 10, it gets coerced to Long.ZERO
```
=> fix(NODE-6144): Long.fromString incorrectly coerces valid inputs to Long.ZERO in special cases

src/long.ts, test/node/bson_type_classes.test.ts, test/node/long.test.ts, test/node/timestamp.test.ts
Refactor `Long.fromBigInt` to only use bit math, and refactor the `Long` constructor to have cleaner logic + remove `Object.assign` calls
Improve performance of `Long.fromBigInt`
No.
Use a more efficient algorithm for `Long.fromBigInt`
Internally fromBigInt was originally implemented using toString of the bigint value. Now, `Long.fromBigInt` has been refactored to use bitwise operations greatly improving performance.
=> perf(NODE-6126): improve Long.fromBigInt performance

.github/workflows/release-5.x.yml, .github/workflows/release.yml
=> chore: use sarif report action from main

.github/workflows/release-5.x.yml, .github/workflows/release.yml
The sbom-lite file is uploaded to s3 upon releases.
=> chore(NODE-6212): upload sbom to s3 during releases and use actions v2

README.md
Updates the release integrity section with links to the GPG key and npm note.
README.md
None
NODE-6235
=> docs(NODE-6235): update release integrity section

src/timestamp.ts, test/node/timestamp.test.ts, test/types/bson.test-d.ts
- add `t` and `i` getters to Timestamp
- change internals to use getters
No
- users do not have to recall whether t or i is the high or low bits
- a Timestamp can be constructed from another Timestamp
To make this type a bit easier to use we are surfacing the breakdown of the two internal 32 bit segments of a Timestamp value.
```ts
const ts = new Timestamp({ i: 2, t: 1 });
ts.i // 2
ts.t // 1
```
=> feat(NODE-6031): add `t` and `i` to Timestamp

.evergreen/config.yml, .evergreen/run-granular-benchmarks.sh, package-lock.json, package.json
Updates benchmarks to run against current branch.
- Sets `LIBRARY` in the environment to the current working directory.
- Updates dbx-js-tools to latest.
- Removes the Node version from the bench task names.
*NOTE* this PR will clear perf benchmark history.
Here's a run pointing at https://github.com/mongodb-js/dbx-js-tools/pull/20
https://spruce.mongodb.com/task/node_bson_perf_run_granular_benchmarks_patch_426c781b3f944bb100a3e70268f3a17210a1178f_66d87ce9c5ee6b0007ef93c4_24_09_04_15_29_49/logs?execution=0
That PR merged, new PR here:
https://spruce.mongodb.com/task/node_bson_perf_run_granular_benchmarks_patch_886391587154866befadc8dd44110411ed54d1ff_66d8e533246d3100075d3bec_24_09_04_22_54_45/logs?execution=0
None
NODE-6358
- Example: `feat(NODE-1234)!: rewriting everything in …
=> test(NODE-6358): perf test against current branch

docs/upgrade-to-v5.md
- Fix missing SerializableTypes section from v5 migration
No
Adding this to the migration guide makes clear our motive and desired path forward
=> docs(NODE-6302): add SerializableTypes to migration guide

src/bson_value.ts, src/constants.ts, src/decimal128.ts, src/extended_json.ts, src/parser/calculate_size.ts, src/parser/serializer.ts, src/parser/utils.ts
This MR improves serialization (and `calculateSize`) performance by up to 20-40% in my tests using MFlix documents.
| Test Case               | Ops/sec (previous) | Ops/sec (new) | Improvement (%) |
|-------------------------|----------------|-------------------|-----------------|
| `serialize`             | 3,102,374      | 3,752,681         | 20.96%          |
| `calculateSize`         | 23,983,120     | 33,635,923        | 40.25%          |
| `serialize large doc`   | 719,650        | 926,643           | 28.76%          |
- `Object.prototype.toString.call(x)` seems to be quite expensive
- Re-order serialization type checks to move these calls out of hot paths
- Add WeakMap cache for repeated calls (ie. calling isDate(x), isRegExp(x), isUint8Array(x) will only result in 1 …
=> perf(NODE-6356): Improve serialization performance

.evergreen/config.yml, .evergreen/run-custom-benchmarks.sh, .gitignore, package.json, test/bench/custom/benchmarks.mjs, test/bench/custom/main.mjs, test/bench/custom/readme.md
- Adds a benchmark suite that will output to our trendcharting tool.
No
- There are a number of code paths that don't relate to serialize/deserialize but can still be useful for critical paths in an application. It would be useful to improve those where we can and ensure we maintain the improvements where they are made.
- Help with the change proposed: https://github.com/mongodb/js-bson/pull/708
=> chore(NODE-6382): add benchmarking for helpers

src/objectid.ts
This MR improves performance of using `ObjectId.isValid('some string')` to check if a string is a valid hex representation of an ObjectId. We frequently call this function to check if a user's input is valid (for example, when creating a document that links to other document(s)).
| Test                        | Ops/s (Main)         | Ops/s (New)          | % Improvement   |
|-----------------------------|----------------------|----------------------|-----------------|
| bson#new ObjectId(string)    | 3,173,643 ops/sec    | 3,299,153 ops/sec    | 3.95%           |
| bson#isValid                | 5,513,041 ops/sec    | 22,529,639 ops/sec   | 308.66%         |
| bson#isValid uppercase      | 5,498,098 ops/sec    | 21,776,208 ops/sec   | 296.07%         |
| bson#isValid invalid end       | …
=> perf(NODE-6344): Improve ObjectId.isValid(string) performance

docs/upgrade-to-v5.md
- Add note about TLA and bundling
No
Clarity on the TLA and bundling subject
=> chore: update migration guide TLA

.evergreen/config.yml, test/node/big_endian.test.ts, test/node/double.test.ts, test/node/release.test.ts
- Add entire suite to zSeries machines to get full coverage on a big endian machine
- Adds Node.js 22 to BSON CI and bump to 22 in tasks that are node version agnostic 
- Skip npm pack test (unnecessary to run on more than one platform)
- fix double test for big endian environment
- Upgraded to RHEL 9 on zSeries because rollup requires GLIBC 2.29+
No
Prepare for future feature work that is endian sensitive.
=> chore(NODE-6018): run entire BSON suite on a big endian machine

src/binary.ts, src/parser/deserializer.ts, test/node/binary.test.ts, test/types/bson.test-d.ts
- Fix Binary.read return type to be correctly Uint8Array
- Use subarray instead of slice so there isn't inconsistent view/copy between node and web
- Prevent reading beyond serializable user data
- Remove dead code from deserializer (buffer.slice is always defined)
- Searched for our usages of slice when we mean to use subarray to get views not copies. This has no impact on Node, fixes browser environments making copies where we did not intend to
No
Correctness and consistency
Binary's `read()` return type claimed it would return `number[]` or Uint8Array which was true in previous BSON versions that didn't _always_ store a Uint8Array on the buffer property like `Binary` does today.
`read()`'s length parameter did not respect the position value allowing reading bytes beyond the data that …
=> fix(NODE-6536): Binary.read never returns number[] and reads beyond content

test/node/bson_binary_vector.spec.test.ts, test/node/specs/bson-binary-vector/float32.json, test/node/specs/bson-binary-vector/int8.json, test/node/specs/bson-binary-vector/packed_bit.json, test/node/specs/bson-corpus/binary.json
- Sync new vector tests in BSON corpus
- Add spec test runner for BSON vector tests
- mark the parts of the test runner with TODOs that need to be in the final API.
Need the test runner to test correctness with respect to the spec. 
Our make/convert APIs will have their own tests so I'm implementing this first to reduce review load. 
=> test(NODE-6534): add spec test runner for Binary vector

.github/dependabot.yml
Adds dependabot config to update Github Actions.
Adds dependabot config to update Github Actions.
None
NODE-6564
=> chore(NODE-6564): add dependabot for github actions

.evergreen/config.yml, .evergreen/install-dependencies.sh, .evergreen/prepare-shell.sh
Pins NPM to 10 with Node.js 18.
Updates dependency script to ensure the pinning.
None
NODE-6634
=> chore(NODE-6634): pin NPM to 10 when Node version is 18

package.json, src/utils/number_utils.ts, test/node/bigint.test.ts
Correct regression to bigint deserialziation introduced in #649 
After refactoring to improve deserialization performance in #649, we inadvertently broke the deserialization of negative Longs into `bigint`. This issue has been fixed here.
Thanks to @rkistner for reporting this bug!
=> fix(NODE-6764): incorrect negative bigint handling

src/utils/number_utils.ts, test/node/bigint.test.ts
After refactoring to improve deserialization performance in #649, we inadvertently introduced a bug that manifested when deserializing `Long` values with the `useBigInt64` flag enabled. The bug would lead to negative `Long` values being deserialized as unsigned integers. This issue has been resolved here.
=> fix(NODE-6812): incorrect negative bigint handling

src/utils/number_utils.ts, test/node/double.test.ts, test/node/utils/number_utils.test.ts
> [!CAUTION]
> Among the platforms BSON and the MongoDB driver support this issue impacts s390x big-endian systems. x86, ARM, and other little-endian systems are not affected. Existing versions of the driver can be upgraded to this release.
A recent change to the BSON library started parsing and serializing floats using a `Float64Array`. When reading the bytes from this array the ordering is dependent on the platform it is running on and we now properly account for that ordering.
=> fix(NODE-6818): flip byte order depending on system endianness

src/utils/number_utils.ts, test/node/bigint.test.ts
After refactoring to improve deserialization performance in #649, we inadvertently introduced a bug that manifested when deserializing `Long` values with the `useBigInt64` flag enabled. The bug would lead to negative `Long` values being deserialized as unsigned integers. This issue has been resolved here.
=> fix(NODE-6829): incorrect negative bigint handling

.evergreen/perf_send.mjs
We do not _need_ to fix this since the fields being added are not used for our perf tracking
=> chore: use todo instead of fixme and remove ticket reference

src/binary.ts, test/node/bson_binary_vector.spec.test.ts, test/node/specs/bson-binary-vector/float32.json, test/node/specs/bson-binary-vector/int8.json, test/node/specs/bson-binary-vector/packed_bit.json
NODE-6735 and NODE-6711
This adds validation to our `BSON.serialize` and `EJSON.stringify` methods that will prevent creating float 32 vectors that are not a multiple of 4. Previously created vectors that do not meet this validation will still be `deserialized` and `parsed` so they can be fixed. 
Additionally, the `toFloat32Array()`, `toInt8Array()`, and `toPackedBits()` methods now perform the same validation that serialize does to prevent use of incorrectly formatted Binary vector values. (For example, a packed bits vector with more than 7 bits of padding)
Vectors of an incorrect length could only be made manually (directly constructing the bytes and calling `new Binary`). We recommend using `toFloat32Array` and `fromFloat32Array` when interacting with Vectors in MongoDB as they handle …
=> fix(NODE-6735, NODE-6711): add BSON vector validation to EJSON stringification, serialization and conversion to native types

etc/rollup/rollup-plugin-require-rewriter/require_rewriter.mjs, package.json, rollup.config.mjs, test/bundling/webpack/readme.md, test/bundling/webpack/webpack.config.js, test/load_bson.js, test/node/byte_utils.test.ts, test/node/exports.test.ts
The bundling process has been changed to make two separate ESM bundles for browsers and Node.js respectively.
No
The main motivation for this change is that the top level async-await usage breaks hot refresh in Next.js when importing this library on the client, as documented in this issue https://github.com/vercel/next.js/issues/61452 with a reproduction in this repo https://github.com/flo-dao/repro-fast-refresh.
The code does execute fine, it's specifically that the hot refresh behavior is broken. This is very problematic on applications that are very stateful and leverage hot refresh to have a quick iteration cycle. The current state is that when changing any module that imports `"bson"` it causes a full-page refresh, and you lose all of the state driving the UI you were developing
This …
=> fix(NODE-6074): Removes top-level await in bson with separate node and browser ESM bundles

package-lock.json, package.json, src/parser/on_demand/parse_to_elements.ts, test/bench/tsconfig.json, test/bundling/webpack/package.json, test/bundling/webpack/tsconfig.json, tsconfig.json
Updates typescript to 5.8.3
- Update typescript.
- Updates dependencies that were out of date with the TS update.
- Enable `erasableSyntaxOnly` option.
None
NODE-6938
=> chore(NODE-6938): update typescript to 5.8.3

release-please-config.json
=> chore(NODE-6975): remove skip-ci from release PR title

release-please-config.json
=> chore(NODE-6974): remove skip-ci from release PR title

src/binary.ts
BSON Binary subtype 2 was previously deprecated in the BSON specification, but the corresponding subtype constant remained available in the BSON library. This constant has now been deprecated to align with the specification.
=> feat(NODE-7099): deprecate BSON binary subtype 2 constant

.github/dependabot.yml
Adding a prod-dependencies group to the dependabot config; technically there are no prod dependencies in bson, but keeping the config consistent across our repos makes it easier to maintain.
Future-proofing convenience of dependency updates
=> chore: Update dependabot.yml to group prod dependencies
