README.md
`bson.BSONPure.BSON` needs to be invoked as a constructor.
=> README fix.

lib/bson/parser/serializer.js, test/node/test_full_bson.js
=> throw error when regexp contains null bytes

README.md, lib/bson/parser/deserializer.js, test/node/bson_test.js, test/node/test_full_bson.js
**promoteBuffers** {Boolean, default:false}
=> add option for deserializing binary into Buffer object

package.json
Re: #174 
Looks like it isn't used anywhere
=> remove one

README.md
Updating readme with ObjectId documentation, clearer serialization/deserialization docs, and npm install instructions
=> ObjectId docs, and other improvements

lib/bson/index.js
It makes using bson with webpack way easier.
=> Make the context explicit

lib/bson/fnv1a.js, lib/bson/objectid.js, test/node/fnv1a.js, test/node/specs/object-id/vectors.json, test/node/specs/object-id/vectors.yml
Uses a hash of the hostname in the object id. Hashing algorithm
is FNV-1a, 24-bit, using xor-folding.
Fixes NODE-1484
=> feat(ObjectID): use FNV-1a hash for objectId

README.md, lib/bson/bson.js, lib/bson/ensure_buffer.js, test/node/bson_test.js, test/node/ensure_buffer_test.js
Re-creating #228, rebasing out duplicated changes.
=> Feat/uint array/handle uint array

.travis.yml, karma.conf.js
This is required by Travis to run our tests in the containerized environment.
=> refactor(karma): start chrome headless without sandbox

lib/binary.js, lib/bson.js, lib/decimal128.js, lib/ensure_buffer.js, lib/objectid.js, lib/parser/deserializer.js, package-lock.json, test/bson_node_only_tests.js, test/node/bson_compliance_test.js, test/node/bson_corpus_tests.js, test/node/bson_test.js, test/node/decimal128_tests.js, test/node/ensure_buffer_test.js, test/node/object_id_tests.js, test/node/promote_values_test.js, test/node/serialize_with_buffer_tests.js, test/node/test_full_bson.js
Replace Buffer constructor with buffer.alloc and buffer.from
Fixes Node-1461
=> fix(buffer): replace deprecated Buffer constructor

lib/parser/serializer.js
=> fix(serializer): do not use checkKeys for $clusterTime

README.md, lib/bson.js, package-lock.json, package.json, tools/README.hbs
This updates our documentation to reflect API changes in 4.0, but also updates the process of generating the documentation to use jsdoc.
=> refactor(docs): update documentation to match 4.x API

README.md
=> docs(Angular): document workaround for Angular 6 global issue

test/node/bson_corpus_tests.js, test/node/specs/bson-corpus/timestamp.json
=> chore: Sync BSON Corpus spec tests

rollup.config.js, src/objectid.ts, src/parser/utils.ts
Removes util dependency and restricts rollup bundler to only include Buffer
NODE-2826
=> refactor: Remove util dependency

package.json
- updated author info with team name and email
- updated bug url to point to Jira instead of GitHub
- removed bug email to drive user to Jira
=> chore(NODE-3316): update author info, update bug url and remove bug email in package.json

src/parser/utils.ts
Removes the util usage infavor of our inlined shim
=> fix(NODE-3561): umd bundle fails to require util

test/node/bson_test.js, test/node/tools/utils.js
Left out the prose tests by accident in the last PR, here they are!
=> test(NODE-3447): prose tests for serialization of BSON with embedded null bytes in strings

.github/workflows/main.yml, .travis.yml, package-lock.json, package.json, test/node/null_byte_test.js, test/node/specs/bson-corpus/document.json, test/node/specs/bson-corpus/regex.json, test/node/specs/bson-corpus/top.json
test serialization of BSON with embedded null bytes in strings [1.x port]
(and adopt GH Actions instead of travis)
=> test(NODE-3617): serialization of BSON with embedded null bytes in strings

.github/pull_request_template.md, .gitignore
Adding .vscode to .gitignore and updating the PR template to match the node driver template
=> chore: update .gitignore and PR template

.evergreen/config.yml, test/register-bson.js
=> chore(NODE-3723): add node 16 to matrix

.evergreen/config.yml, .evergreen/setup-environment.sh
Adds latest node into CI.
Nope.
=> ci(NODE-4204): add support for latest node version in CI

docs/upgrade-to-v5.md
=> docs(NODE-4794): Clean up migration guide for BSON v5

.evergreen/config.yml, .evergreen/init-nvm.sh, .evergreen/install-dependencies.sh, .evergreen/run-checks.sh, .evergreen/run-eslint-plugin-test.sh, .evergreen/run-tests.sh, .evergreen/setup-environment.sh, test/register-bson.js
Add nodejs fetching script from https://github.com/mongodb/node-mongodb-native/pull/3583
=> ci(NODE-5087): download node to local directory

.github/actions/setup/action.yml, .github/pull_request_template.md, .github/scripts/highlights.mjs, .github/scripts/pr_list.mjs, .github/scripts/release_notes.mjs, .github/scripts/util.mjs, .github/workflows/release.yml, .github/workflows/release_notes.yml, package-lock.json, package.json
Adds release automation from driver
no
- Release with provenance
- Automated notes system
=> chore(NODE-5383): add release automation

sbom.json
=> chore(NODE-6142): add sbom lite file to BSON

.github/scripts/highlights.mjs, .github/workflows/release.yml, .github/workflows/release_notes.yml, package-lock.json, package.json
- update release please owner
- make highlight use fetch and remove octokit
- new source for release please
- using fetch and "repository" variable makes copy pasting to other repos easier because there's now no owner/repo varaibles in the script that has to be changed.
=> chore(NODE-6170): update release please owner

sbom.json
=> chore: add sbom-lite file to 5.x

.github/workflows/release-6.4.yml
=> chore(NODE-6811): add 6.4 release action

.github/workflows/release-6.4.yml
=> chore(NODE-6814): add 6.4 release action to 6.4 branch

.github/scripts/highlights.mjs, .github/workflows/build.yml, .github/workflows/release_notes.yml, sbom.json
=> chore(NODE-6815): sync build script to 6.4 branch
